variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_OPTS: ''
  IMAGE_NAME: docker.felix.dev/felix/felix.dev/web
  IMAGE_CI_REF: ${IMAGE_NAME}:$CI_COMMIT_SHA-$CI_PIPELINE_ID
  IMAGE_DEV_REF: ${IMAGE_NAME}:dev
  IMAGE_PROD_REF: ${IMAGE_NAME}:latest

stages:
  - build
  - deploy

.docker_setup: &docker_setup
  before_script:
    - docker login -u gitlab-ci-token --password-stdin "${CI_REGISTRY}" <<<"${CI_JOB_TOKEN}" > /dev/null 2>&1
    - docker buildx create --use --name ci --platform linux/arm64,linux/amd64

build-dev:
  <<: *docker_setup
  stage: build
  script:
    - docker buildx build --tag "${IMAGE_DEV_REF}" --tag "${IMAGE_CI_REF}" --push --pull --platform linux/arm64,linux/amd64 ${BUILD_OPTS} .
  only:
    - dev

build-prod:
  <<: *docker_setup
  stage: build
  script:
    - docker buildx build --tag "${IMAGE_PROD_REF}" --tag "${IMAGE_CI_REF}" --push --pull --platform linux/arm64,linux/amd64 ${BUILD_OPTS} .
  only:
    - master

deploy-test:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - echo "${IMAGE_CI_REF}"
    - kubectl --kubeconfig "${KUBE_CONFIG}" --namespace felix set image deployment/test-felix-dev "web=${IMAGE_CI_REF}"
  only:
    - dev

deploy-prod:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  script:
    - echo "${IMAGE_CI_REF}"
    - kubectl --kubeconfig "${KUBE_CONFIG}" --namespace felix set image deployment/felix-dev "web=${IMAGE_CI_REF}"
  only:
    - master
