variables:
  BUILD_OPTS: ""
  IMAGE_NAME: docker.felix.dev/felix.dev

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'echo "docker image: $IMAGE_NAME:$CI_COMMIT_SHA-$CI_PIPELINE_ID"'
    - docker-build $IMAGE_NAME $CI_COMMIT_SHA-$CI_PIPELINE_ID . "${BUILD_OPTS}"
  only:
    - master

deploy-test:
  stage: deploy
  script:
    - kubectl --kubeconfig "${KUBE_CONFIG}" --namespace felix set image deployment/test-felix-dev test-felix-dev=$IMAGE_NAME:$CI_COMMIT_SHA-$CI_PIPELINE_ID
  only:
    - dev

deploy:
  stage: deploy
  script:
    - kubectl --kubeconfig "${KUBE_CONFIG}" --namespace felix set image deployment/felix-dev felix-dev=$IMAGE_NAME:$CI_COMMIT_SHA-$CI_PIPELINE_ID
  only:
    - master