title = "Felix Klein"
theme = "felix"
paginate = 3
publishDir = "dist"

pygmentsCodeFences = true
pygmentsUseClasses = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Felix Klein"
    keywords = ""
    copyright = "(c) 2019 Felix Klein"
    menuMore = "Show more"
    readMore = "Read more"

    [languages.en.params.logo]
      logoText = "Felix Klein"
      logoHomeLink = "/"

[blackfriday]
    noreferrerLinks = true