title = "Felix Klein"
theme = "felix"
paginate = 3
publishDir = "dist"

[languages]
  [languages.en]
    languageName = "English"
    title = "Felix Klein"
    keywords = ""
    copyright = "(c) 2019 Felix Klein"
    menuMore = "Show more"
    readMore = "Read more"

    [languages.en.params.logo]
      logoText = "Felix Klein"
      logoHomeLink = "/"

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2
